bot:
  token: 6012510763:test
ecb:
  eurofxref-daily-xml-url: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

spring:
  sql:
    init:
      mode: always
#  config:
#    activate:
#      on-profile: ci,test
  datasource:
    url: jdbc:h2:mem:finconbot
    username: test
    password: test